[tool.pylint.message_control]

disable = [
    "missing-function-docstring",
    "missing-module-docstring",
    "missing-class-docstring",
    "too-few-public-methods",
    "missing-final-newline",
    "invalid-name",
]

[tool.black]
line-length = 90
skip-string-normalization = true
target-version = ['py39']

[tool.isort]
multi_line_output = 3
length_sort = true
