services:
  backend:
    image: ${LOCAL_IMAGE_NAME}
    ports:
      - "8080:8080"

    environment:
      - PREDICTION_STREAM_NAME=ride_predictions
      - TEST_RUN=True
      - AWS_DEFAULT_REGION=eu-west-1
      - RUN_ID=Test123
      - MODEL_LOCATION=/app/model
    volumes:
      - "./model:/app/model"
